/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WppRouteImport } from './routes/wpp'
import { Route as IndexRouteImport } from './routes/index'

const WppRoute = WppRouteImport.update({
  id: '/wpp',
  path: '/wpp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wpp': typeof WppRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wpp': typeof WppRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/wpp': typeof WppRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/wpp'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/wpp'
  id: '__root__' | '/' | '/wpp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WppRoute: typeof WppRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wpp': {
      id: '/wpp'
      path: '/wpp'
      fullPath: '/wpp'
      preLoaderRoute: typeof WppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WppRoute: WppRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
